image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

deploy_production:
  stage: deploy
  variables:
   GIT_STRATEGY: none
  script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - curl -X POST -F token=$INFRASTRUCTURE_TOKEN -F ref=master -F "variables[DEPLOY_APP]=$CI_PROJECT_NAME" -F "variables[DEPLOY_IMAGE]=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" -F "variables[DEPLOY_URL]=cfischer.io" -F "variables[DEPLOY_ACTION]=start" https://gitlab.com/api/v4/projects/9512925/trigger/pipeline --silent --show-error --fail
  environment:
    name: production
    url: https://cfischer.io
  only:
    - master

deploy_review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - curl -X POST -F token=$INFRASTRUCTURE_TOKEN -F ref=master -F "variables[DEPLOY_APP]=$CI_PROJECT_NAME" -F "variables[DEPLOY_IMAGE]=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" -F "variables[DEPLOY_URL]=$CI_COMMIT_REF_SLUG.cfischer.io" -F "variables[DEPLOY_ACTION]=start" https://gitlab.com/api/v4/projects/9512925/trigger/pipeline --silent --show-error --fail
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://$CI_COMMIT_REF_SLUG-review.cfischer.io
    on_stop: stop_review
  only:
    - branches
  except:
    - master

stop_review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - curl -X POST -F token=$INFRASTRUCTURE_TOKEN -F ref=master -F "variables[DEPLOY_APP]=$CI_PROJECT_NAME" -F "variables[DEPLOY_IMAGE]=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" -F "variables[DEPLOY_URL]=$CI_COMMIT_REF_SLUG.cfischer.io" -F "variables[DEPLOY_ACTION]=stop" https://gitlab.com/api/v4/projects/9512925/trigger/pipeline --silent --show-error --fail
  when: manual
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop